"""
ALIAS_X · Consent Manager
Generates a verification consent PDF using fpdf2.
Falls back to plain text if fpdf is unavailable.
"""

import os
import time


def clean_text(text: str) -> str:
    if not text:
        return "Unknown"
    return str(text).encode("latin-1", "replace").decode("latin-1")


def generate_consent_pdf(student_name: str, university_name: str,
                          output_dir: str = "output_documents") -> str:
    os.makedirs(output_dir, exist_ok=True)

    safe_name = clean_text(student_name)
    safe_uni  = clean_text(university_name)
    ref_id    = f"ALIASX-{int(time.time())}"
    date_str  = time.strftime("%Y-%m-%d", time.gmtime())

    try:
        from fpdf import FPDF

        pdf = FPDF()
        pdf.add_page()

        # ── Title ──────────────────────────────────────────────
        pdf.set_font("Arial", "B", 16)
        pdf.cell(0, 10, "CONSENT FORM FOR EDUCATION VERIFICATION", ln=1, align="C")
        pdf.ln(4)

        # ── Ref / Date ─────────────────────────────────────────
        pdf.set_font("Arial", "I", 10)
        pdf.cell(0, 6, f"Reference ID: {ref_id}    |    Date: {date_str}", ln=1, align="C")
        pdf.ln(8)

        # ── Divider ────────────────────────────────────────────
        pdf.set_draw_color(255, 0, 60)
        pdf.set_line_width(0.8)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(8)

        # ── Body ───────────────────────────────────────────────
        pdf.set_font("Arial", size=12)
        body = (
            f"I, {safe_name}, hereby authorize {safe_uni} to release information "
            "regarding my academic record to ALIAS_X Verification Systems for the "
            "purpose of background verification.\n\n"
            "This consent is valid for 30 days from the date of generation.\n\n"
            "By proceeding with the ALIAS_X verification protocol, the subject "
            "acknowledges and consents to the automated academic verification process."
        )
        pdf.multi_cell(0, 8, txt=body)
        pdf.ln(16)

        # ── Signature ──────────────────────────────────────────
        pdf.set_font("Arial", "I", 10)
        pdf.cell(0, 8, "Signed: (Electronically Generated by ALIAS_X)", ln=1)
        pdf.cell(0, 8, f"ALIAS_X Autonomous Verification Protocol v2.4.1", ln=1)

        # ── Safe filename ──────────────────────────────────────
        safe_fn = "".join(c for c in safe_name if c.isalnum() or c in " _").strip()
        safe_fn = safe_fn.replace(" ", "_") or "Subject"
        output_path = os.path.join(output_dir, f"{safe_fn}_Consent_{ref_id}.pdf")

        try:
            pdf.output(output_path)
        except Exception:
            output_path = os.path.join(output_dir, f"Consent_{ref_id}.pdf")
            pdf.output(output_path)

        print(f"[CONSENT] PDF generated: {output_path}")
        return output_path

    except ImportError:
        # Fallback to plain text
        txt_path = os.path.join(output_dir, f"Consent_{ref_id}.txt")
        with open(txt_path, "w") as f:
            f.write(f"ALIAS_X — EDUCATION VERIFICATION CONSENT\n")
            f.write(f"{'='*50}\n")
            f.write(f"Reference ID : {ref_id}\n")
            f.write(f"Date         : {date_str}\n\n")
            f.write(f"Student      : {safe_name}\n")
            f.write(f"University   : {safe_uni}\n\n")
            f.write(
                f"I, {safe_name}, hereby authorize {safe_uni} to release "
                "information regarding my academic record to ALIAS_X Verification "
                "Systems for the purpose of background verification.\n\n"
                "This consent is valid for 30 days from the date of generation.\n"
            )
            f.write(f"\nSigned: (Electronically Generated by ALIAS_X)\n")
        print(f"[CONSENT] TXT fallback generated: {txt_path}")
        return txt_path
